# Generated by Django 3.2.13 on 2023-08-23 05:03

import blob.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=blob.models.Session.generator, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blob.sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blob.session'),
            preserve_default=False,
        ),
    ]
